services:
  - type: web
    name: calculadora-ci
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
